config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    resources :locations
    resources :posts
    resources :users
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

end

app/models/location.rb
class Location < ActiveRecord::Base
    has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :location
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts
    has_secure_password
    validates(:username, presence: true)
    validates(:email, presence: true)
    validates(:password, length:{minimum:6}, presence: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index
    end
    def new
        @location=Location.new
    end
    def create
        @location=Location.new(location_params)
        @location.save
    end
    def edit
    end
    def show
    end
    def update
    end
    def destroy
    end
    
    private
    def location_params
        params.require(:location).permit(:country, :area, :picture)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
    end
     def new
        @post = Post.new
         @location=Location.new
    end
     def create
         @post=Post.new(post_params)
         @post.user_id = current_user.id
         @post.save
         @location=Location.new(location_params)
         @location.save
         redirect_to @post
    end
    def edit
    end
    def show
        @post=Post.find(params[:id])
    end
    def update
    end
    def destroy
    end
    
    private
    def post_params
        params.require(:post).permit(:user_id, :title, :date, :body)
    end
     def location_params
        params.require(:location).permit(:country, :area, :picture)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        @user=User.find_by(username: params[:session][:username].downcase)
        if @user && @user.authenticate(params[:session][:password])
            log_in @user
            redirect_to root_path
        else
        render 'new'
        end
    end
    def destroy
        log_out
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end
    def create
        @user=User.new(user_params)
        @user.save
        log_in(@user)
        redirect_to root_path
    end
    def new
        @user=User.new
    end
    def edit
    end
    def show
        @user=User.find(params[:id])
    end
    def update
    end
    def destroy
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @posts=Post.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id]=user.id
    end
    def current_user
        @current_user=User.find_by(id: session[:user_id])
    end
    def log_out
        session.delete(:user_id)
        @current_user=nil
    end
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelDiaries</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<div id="head"><p><%= link_to 'Home', root_path%>  <%=current_user.username%></p></div>

<div><h1>Create a new post:</h1></div>
<div><%=form_for @post do |f|%>
    <%=fields_for @location do |fa|%>
        <p><%=fa.label :country%><br>
        <%=fa.text_field :country%></p>
        <p><%=fa.label :area%><br>
        <%=fa.text_field :area%></p>
        <p><%=fa.label :picture%><br>
            <%=fa.text_field :picture, placeholder: "Paste a URL here"%></p>
        <%end%>
    <p><%=f.label :title%><br>
    <%=f.text_field :title%></p>
    <p><%=f.label :date%><br>
        <%=f.date_field :date, placeholder: "mm/dd/yyyy"%></p>
    <p><%=f.label :body%><br>
    <%=f.text_area :body, placeholder: "Tell us about your trip"%></p>
    <%f.text_field :user, value: current_user[:username]%>
    <%=f.submit "Submit Post"%></div>
<%end%>

app/views/posts/show.html.erb
<div id="head"><%=link_to 'Home', root_path%></div>
<div><h1><%=@post.title%></h1></div>
<div><p><%=@post.date%></p>
<p><%=@post.body%></p>

    <p><%=User.find_by(@post.user_id).username%></p>
</div>

app/views/users/new.html.erb
<h1>Create a user account:</h1>
<%if @user.errors.any?%>
    <ul>@user.errors.full_messages.each do |msg|
        <li><%=msg%></li>
    </ul>
<%end%>
<%=form_for(@user) do |f|%>
    <p><%=f.label :username%><br>
    <%=f.text_field :username%></p>
    <p><%=f.label :email%><br>
    <%=f.email_field :email%></p>
    <p><%=f.label :password%><br>
    <%=f.password_field :password%><br></p>
    <p><%=f.label :password_confirmation%><br>
    <%=f.password_field :password_confirmation%></p>
    <p><%=f.submit "Create Account"%></p>
<%end%>

app/views/welcome/index.html.erb
<%if logged_in?%>
    <div id="head"><p><%=link_to "New Post", new_post_path%>  <%=current_user.username%>  <%=link_to "logout", logout_path, method: :delete%></p></div>
<%else%>
        <div id="head"><p><%= link_to "Signup", new_user_path%>  <%= link_to "Login", login_path%></p></div>
<%end%>
<div><h1>Welcome to TravelDiary</h1>
    <p>This is a website for you to share your experiences</p>
    <p>You can read everyone else's posts below, or you can sign up for an account and create your own!</p>
</div>
<%@posts.order('created_at DESC').each do |post|%>
<br><div><h2><%=post.title%></h2><br>
    
    <%=post.body%><br>
<%=User.find_by(id: post.user_id).username%></div>
<%end%>